events {
    worker_connections 1024;
}

http {
    upstream hodor {
        server hodor:8080;
    }

    upstream bran {
        server bran:8000;
    }

    server {
        listen 80;

        location /hodr/ {
            proxy_pass http://hodor;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /bran/ {
            proxy_pass http://bran;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://hodor;
        }
    }
}